# Generated by Django 5.0.7 on 2024-09-06 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 23, 41, 35, 755465, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='postimage_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 23, 41, 35, 756464, tzinfo=datetime.timezone.utc)),
        ),
    ]
