# Generated by Django 5.0.7 on 2024-08-09 18:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_alter_courses_course_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_video', models.FileField(upload_to='video/%y/%m/%d')),
                ('video_title', models.CharField(max_length=50)),
                ('video_desc', models.CharField(max_length=800)),
                ('video_time', models.DateTimeField(default=datetime.datetime(2024, 8, 9, 19, 23, 22, 638217))),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
    ]
