# Generated by Django 5.0.7 on 2024-09-07 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_alter_videos_video_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 23, 18, 20, 819211)),
        ),
    ]
