# Generated by Django 4.1.10 on 2024-08-05 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('channel_name', models.CharField(default='Unknown', max_length=15, validators=[django.core.validators.MinLengthValidator(3)])),
                ('channel_email', models.EmailField(max_length=254, unique=True)),
                ('channel_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')])),
                ('channel_desc', models.TextField(blank=True, max_length=275)),
                ('channel_img', models.CharField(blank=True, max_length=20)),
                ('channel_likes', models.IntegerField(default=0)),
                ('channel_teacher', models.BooleanField(default=False)),
                ('channel_verifycode', models.CharField(blank=True, max_length=6)),
                ('channel_approve', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
