# Generated by Django 4.1.10 on 2024-08-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_channel_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_img',
            field=models.ImageField(blank=True, null=True, upload_to='channel_images/'),
        ),
    ]
