# Generated by Django 5.0.7 on 2024-08-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_createchannel_channel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createchannel',
            name='channel_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
