# Generated by Django 5.0.7 on 2024-08-08 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortvideo', '0004_alter_shortvideo_short_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortvideo',
            old_name='channel_id',
            new_name='channel',
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='short_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 22, 59, 48, 388338)),
        ),
    ]
