# Generated by Django 5.0.7 on 2024-08-08 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortvideo', '0008_alter_shortvideo_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortvideo',
            name='short_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 23, 34, 35, 807711)),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='short_video',
            field=models.FileField(null=True, upload_to='shortvideo/%y/%m/%d'),
        ),
    ]
