# Generated by Django 5.0.7 on 2024-08-08 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortvideo', '0012_alter_shortvideo_short_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortvideo',
            name='short_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 0, 6, 52, 238237)),
        ),
    ]
