# Generated by Django 5.0.7 on 2024-08-08 23:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_channel_channel_img'),
        ('shortvideo', '0013_alter_shortvideo_short_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortvideo',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.channel'),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='short_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='short_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='short_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 0, 9, 34, 726827)),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='short_title',
            field=models.CharField(max_length=100),
        ),
    ]
