# Generated by Django 5.0.7 on 2024-08-09 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courses_course_time_alter_courses_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 19, 23, 22, 623315)),
        ),
    ]
