# Generated by Django 5.0.7 on 2024-09-06 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_courses_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 12, 45, 11, 362560)),
        ),
    ]
