# Generated by Django 4.1.10 on 2024-08-05 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(default='Unknown', max_length=150, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
