# Generated by Django 5.0.7 on 2024-08-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createchannel',
            name='channel_verifycode',
            field=models.CharField(default=406426, max_length=6),
        ),
    ]
