# Generated by Django 5.0.7 on 2024-08-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_createchannel_channel_verifycode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createchannel',
            old_name='channel_aprove',
            new_name='channel_approve',
        ),
        migrations.RemoveField(
            model_name='createchannel',
            name='channel_createAT',
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_desc',
            field=models.TextField(max_length=275),
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_img',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_likes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_type',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_verifycode',
            field=models.CharField(max_length=6),
        ),
    ]
