# Generated by Django 5.0.7 on 2024-08-03 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_channel_aprove_createchannel_channel_approve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createchannel',
            name='channel_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
