# Generated by Django 5.0.7 on 2024-08-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_createchannel_channel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createchannel',
            name='channel_time',
        ),
    ]
