# Generated by Django 5.0.7 on 2024-08-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_createchannel_channel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createchannel',
            name='channel_password',
            field=models.CharField(max_length=254),
        ),
    ]
