# Generated by Django 5.0.7 on 2024-08-03 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_createchannel_channel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='createchannel',
            name='channel_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 23, 40, 13, 452613)),
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_type',
            field=models.BooleanField(default=False),
        ),
    ]
