# Generated by Django 5.0.7 on 2024-08-03 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_createchannel_channel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createchannel',
            name='channel_time',
        ),
        migrations.AddField(
            model_name='createchannel',
            name='channel_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 23, 47, 27, 943938)),
        ),
    ]
