# Generated by Django 5.0.7 on 2024-08-03 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_createchannel_channel_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 0, 7, 48, 11936)),
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_email',
            field=models.CharField(max_length=254),
        ),
    ]
