# Generated by Django 5.0.7 on 2024-08-03 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_createchannel_channel_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createchannel',
            name='channel_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 0, 23, 8, 19328)),
        ),
    ]
