# Generated by Django 5.0.7 on 2024-08-04 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_createchannel_channel_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckEmail',
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 22, 56, 48, 616151)),
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_verifycode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
