# Generated by Django 5.0.7 on 2024-08-04 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_delete_checkemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createchannel',
            name='channel_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 23, 4, 14, 687816)),
        ),
        migrations.AlterField(
            model_name='createchannel',
            name='channel_verifycode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
