# Generated by Django 5.0.7 on 2024-08-04 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_createchannel_channel_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createchannel',
            name='channel_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 0, 25, 12, 143036)),
        ),
    ]
